/*
 * In The Name Of God
 * ========================================
 * [] File Name : exception.c
 *
 * [] Creation Date : 27-12-2014
 *
 * [] Last Modified : Wed 07 Jan 2015 04:10:53 AM IRST
 *
 * [] Created By : Parham Alvani (parham.alvani@gmail.com)
 * =======================================
*/
#include "exception.h"
#include "isr.h"
#include <monitor.h>

/*
 * This interrupt is generated when the CPU attempts to execute an
 * invalid opcode (most protected-mode instructions are considered
 * invalid in real mode) or a BOUND, LDS, LES, or LIDT instruction
 * which specifies a register rather than a memory address
*/
static void exception_callback_6(registers_t regs)
{
	puts("Invalid Opcode\n");
}

/*
 * Generated by BOUND instruction when the value to be tested is less
 * than the indicated lower bound or greater than the indicated upper bound.
*/
static void exception_callback_5(registers_t regs)
{

}

/*
 * The INTO instruction will generate this interrupt if
 * OF (Overflow Flag) is set; otherwise, INTO is effectively a NOP
*/
static void exception_callback_4(registers_t regs)
{

}

/*
 * Generated by the one-byte breakpoint instruction (opcode CCh)
*/
static void exception_callback_3(registers_t regs)
{
	puts("Breakpoint Occur\n");
}

void init_exception(void)
{
	register_interrupt_handler(6, &exception_callback_6);
	register_interrupt_handler(5, &exception_callback_5);
	register_interrupt_handler(4, &exception_callback_4);
	register_interrupt_handler(3, &exception_callback_3);
}
